### ISSUE TITLE
cant use if have unites and group

### ISSUE THREAD

**Issue by MirabellaBlack** [arcygarcy/doodleTrainer#1]
doesn't account for pets being in the 5th spot

**Comment by arcygarcy** [comment]
personally i would recommend making a new account to use it on to try and prevent good accounts from getting temp banned. Im not sure if I have the source code still, if I do, ill try and fix it and push it out.

**Comment by arcygarcy** [comment]
Updated readme to reflect this information see [this](https://github.com/arcygarcy/doodleTrainer/commit/582646e3f74d603a110f93320648bcf4d1f214fb)

Thanks, for the comment

**Comment by arcygarcy** [comment]
Updated readme to reflect this information see [this](https://github.com/arcygarcy/doodleTrainer/commit/582646e3f74d603a110f93320648bcf4d1f214fb)

Thanks, for the comment
